packages:
  - docs
  - examples/*
  - packages/*
catalog:
  "@biomejs/biome": 2.2.6
  "@changesets/cli": 2.29.0
  "@hookform/resolvers": ^2.9.11
  "@radix-ui/react-accessible-icon": ^1.1.3
  "@radix-ui/react-accordion": ^1.2.4
  "@radix-ui/react-alert-dialog": ^1.1.7
  "@radix-ui/react-aspect-ratio": ^1.1.3
  "@radix-ui/react-avatar": ^1.1.4
  "@radix-ui/react-checkbox": ^1.1.5
  "@radix-ui/react-collapsible": ^1.1.4
  "@radix-ui/react-context-menu": ^2.2.7
  "@radix-ui/react-dialog": ^1.1.7
  "@radix-ui/react-dropdown-menu": ^2.1.7
  "@radix-ui/react-hover-card": ^1.1.7
  "@radix-ui/react-label": ^2.1.3
  "@radix-ui/react-menubar": ^1.1.7
  "@radix-ui/react-navigation-menu": ^1.2.6
  "@radix-ui/react-popover": ^1.1.7
  "@radix-ui/react-progress": ^1.1.3
  "@radix-ui/react-radio-group": ^1.2.4
  "@radix-ui/react-scroll-area": ^1.2.4
  "@radix-ui/react-select": ^2.1.7
  "@radix-ui/react-separator": ^1.1.3
  "@radix-ui/react-slider": ^1.2.4
  "@radix-ui/react-slot": ^1.2.0
  "@radix-ui/react-switch": ^1.1.4
  "@radix-ui/react-tabs": ^1.1.4
  "@radix-ui/react-toast": ^1.2.7
  "@radix-ui/react-toggle": ^1.1.3
  "@radix-ui/react-toggle-group": ^1.1.3
  "@radix-ui/react-tooltip": ^1.2.0
  "@supabase/auth-helpers-nextjs": 0.8.7
  "@supabase/auth-helpers-react": 0.4.2
  "@supabase/postgrest-js": 1.21.4
  "@supabase/storage-js": 2.12.1
  "@tailwindcss/postcss": ^4.1.4
  "@tanstack/react-query": 5.74.4
  "@testing-library/react": 16.3.0
  "@types/flat": 5.0.2
  "@types/lodash": 4.17.0
  "@types/node": 22.14.1
  "@types/react": 19.1.2
  "@types/react-dom": 19.1.2
  "@types/uuid": ^9.0.2
  "@vitest/coverage-istanbul": ^3.0.0
  autoprefixer: ^10.4.13
  class-variance-authority: 0.7.0
  clsx: ^1.2.1
  fast-equals: 5.2.2
  flat: 6.0.1
  happy-dom: 17.6.1
  ioredis: 5.6.1
  lucide-react: 0.488.0
  merge-anything: 5.1.7
  next: 15.3.1
  next-themes: ^0.2.1
  nextra: 4.2.17
  nextra-theme-docs: 4.2.17
  postcss: ^8.4.14
  react-hook-form: 7.55.0
  server-only: ^0.0.1
  sharp: ^0.31.3
  supabase: 2.22.2
  swr: 2.3.3
  tailwind-merge: ^1.10.0
  tailwindcss: 4.1.4
  tailwindcss-animate: ^1.0.5
  tsup: 8.5.0
  tw-animate-css: ^1.2.5
  uuid: ^9.0.0
  vitest: 3.2.0
  xregexp: 5.1.1
  zod: ^3.21.4
  "@supabase/supabase-js": 2.57.4
  "@vercel/analytics": 1.5.0
  dotenv: 16.6.0
  react: 19.1.0
  react-dom: 19.1.0
  turbo: 2.5.0
  typescript: 5.8.3
