packages:
  - docs
  - examples/*
  - packages/*
  - tools/*
catalog:
  "@biomejs/biome": 1.9.4
  "@changesets/cli": 2.29.0
  "@supabase/postgrest-js": 1.21.4
  "@supabase/storage-js": 2.12.1
  "@supabase/supabase-js": 2.57.4
  "@testing-library/react": 16.3.0
  "@types/flat": 5.0.2
  "@types/lodash": 4.17.0
  "@types/node": 22.14.1
  "@types/react": 19.1.2
  "@types/react-dom": 19.1.2
  "@vercel/analytics": 1.5.0
  "@vitest/coverage-istanbul": ^3.0.0
  autoprefixer: ^10.4.13
  dotenv: 16.6.0
  fast-equals: 5.2.2
  flat: 6.0.1
  happy-dom: 17.6.1
  ioredis: 5.6.1
  merge-anything: 5.1.7
  next: 15.3.1
  nextra: 4.2.17
  nextra-theme-docs: 4.2.17
  postcss: ^8.4.14
  react: 19.1.0
  react-dom: 19.1.0
  server-only: ^0.0.1
  supabase: 2.22.2
  tailwindcss: 4.1.4
  tsup: 8.5.0
  turbo: 2.5.0
  typescript: 5.8.3
  vitest: 3.2.0
  xregexp: 5.1.1
