packages:
  - docs
  - examples/*
  - packages/*
  - tools/*
catalog:
  "@changesets/cli": 2.29.0
  "@supabase/postgrest-js": 1.21.4
  "@supabase/storage-js": 2.12.1
  "@supabase/supabase-js": 2.57.4
  "@testing-library/react": 16.3.0
  "@types/flat": 5.0.2
  "@types/lodash": 4.17.0
  "@types/react": 19.1.2
  "@vitest/coverage-istanbul": ^3.0.0
  dotenv: 17.2.3
  fast-equals: 5.2.2
  flat: 6.0.1
  happy-dom: 20.0.11
  ioredis: 5.6.1
  merge-anything: 5.1.7
  react: 19.1.0
  react-dom: 19.1.0
  server-only: ^0.0.1
  supabase: 2.22.2
  tsup: 8.5.0
  turbo: 2.5.0
  typescript: 5.8.3
  oxfmt: 0.20.0
  oxlint: 1.33.0
  vitest: 3.2.0
  xregexp: 5.1.1
