packages:
  - docs
  - examples/*
  - packages/*
  - tools/*
catalog:
  "@changesets/cli": 2.29.8
  "@supabase/postgrest-js": 2.90.0
  "@supabase/storage-js": 2.90.0
  "@supabase/supabase-js": 2.90.0
  "@testing-library/react": 16.3.1
  "@types/flat": 5.0.5
  "@types/lodash": 4.17.21
  "@types/react": 19.2.7
  "@vitest/coverage-istanbul": 4.0.16
  dotenv: 17.2.3
  fast-equals: 6.0.0
  flat: 6.0.1
  happy-dom: 20.0.11
  ioredis: 5.9.0
  merge-anything: 5.1.7
  react: 19.2.3
  react-dom: 19.2.3
  server-only: ^0.0.1
  supabase: 2.71.0
  tsup: 8.5.1
  turbo: 2.7.2
  typescript: 5.9.3
  oxfmt: 0.23.0
  oxlint: 1.38.0
  vitest: 4.0.16
  xregexp: 5.1.2
